// Code generated by "stringer -type Diff -trimprefix Diff"; DO NOT EDIT.

package semver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Same-0]
	_ = x[DiffOther-1]
	_ = x[DiffMajor-2]
	_ = x[DiffMinor-3]
	_ = x[DiffPatch-4]
	_ = x[DiffPrerelease-5]
	_ = x[DiffBuild-6]
}

const _Diff_name = "SameOtherMajorMinorPatchPrereleaseBuild"

var _Diff_index = [...]uint8{0, 4, 9, 14, 19, 24, 34, 39}

func (i Diff) String() string {
	if i < 0 || i >= Diff(len(_Diff_index)-1) {
		return "Diff(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Diff_name[_Diff_index[i]:_Diff_index[i+1]]
}
