// Code generated by "stringer -type System"; DO NOT EDIT.

package semver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultSystem-0]
	_ = x[Cargo-1]
	_ = x[Go-2]
	_ = x[Maven-3]
	_ = x[NPM-4]
	_ = x[NuGet-5]
	_ = x[PyPI-6]
	_ = x[RubyGems-7]
	_ = x[Composer-8]
}

const _System_name = "DefaultSystemCargoGoMavenNPMNuGetPyPIRubyGemsComposer"

var _System_index = [...]uint8{0, 13, 18, 20, 25, 28, 33, 37, 45, 53}

func (i System) String() string {
	if i >= System(len(_System_index)-1) {
		return "System(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _System_name[_System_index[i]:_System_index[i+1]]
}
