// Code generated by "stringer -type tokType -trimprefix tok"; DO NOT EDIT.

package semver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokInvalid-0]
	_ = x[tokInternalError-1]
	_ = x[tokEmpty-2]
	_ = x[tokEqual-3]
	_ = x[tokGreater-4]
	_ = x[tokGreaterEqual-5]
	_ = x[tokLess-6]
	_ = x[tokLessEqual-7]
	_ = x[tokNotEqual-8]
	_ = x[tokCaret-9]
	_ = x[tokTilde-10]
	_ = x[tokBacon-11]
	_ = x[tokComma-12]
	_ = x[tokOr-13]
	_ = x[tokHyphen-14]
	_ = x[tokLbracket-15]
	_ = x[tokRbracket-16]
	_ = x[tokVersion-17]
	_ = x[tokWildcard-18]
	_ = x[tokEOF-19]
}

const _tokType_name = "InvalidInternalErrorEmptyEqualGreaterGreaterEqualLessLessEqualNotEqualCaretTildeBaconCommaOrHyphenLbracketRbracketVersionWildcardEOF"

var _tokType_index = [...]uint8{0, 7, 20, 25, 30, 37, 49, 53, 62, 70, 75, 80, 85, 90, 92, 98, 106, 114, 121, 129, 132}

func (i tokType) String() string {
	if i < 0 || i >= tokType(len(_tokType_index)-1) {
		return "tokType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokType_name[_tokType_index[i]:_tokType_index[i+1]]
}
