// Code generated by "stringer -type AttrKey -output stringer.go"; DO NOT EDIT.

package dep

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Dev - -1]
	_ = x[Opt - -2]
	_ = x[Test - -4]
	_ = x[XTest-1]
	_ = x[Framework-2]
	_ = x[Scope-3]
	_ = x[MavenClassifier-4]
	_ = x[MavenArtifactType-5]
	_ = x[MavenDependencyOrigin-6]
	_ = x[MavenExclusions-9]
	_ = x[EnabledDependencies-7]
	_ = x[KnownAs-8]
	_ = x[Environment-10]
	_ = x[Selector-11]
}

const (
	_AttrKey_name_0 = "Test"
	_AttrKey_name_1 = "OptDev"
	_AttrKey_name_2 = "XTestFrameworkScopeMavenClassifierMavenArtifactTypeMavenDependencyOriginEnabledDependenciesKnownAsMavenExclusionsEnvironmentSelector"
)

var (
	_AttrKey_index_1 = [...]uint8{0, 3, 6}
	_AttrKey_index_2 = [...]uint8{0, 5, 14, 19, 34, 51, 72, 91, 98, 113, 124, 132}
)

func (i AttrKey) String() string {
	switch {
	case i == -4:
		return _AttrKey_name_0
	case -2 <= i && i <= -1:
		i -= -2
		return _AttrKey_name_1[_AttrKey_index_1[i]:_AttrKey_index_1[i+1]]
	case 1 <= i && i <= 11:
		i -= 1
		return _AttrKey_name_2[_AttrKey_index_2[i]:_AttrKey_index_2[i+1]]
	default:
		return "AttrKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
