// Code generated by gen-platform-tags.py; DO NOT EDIT.
// This was generated at Mon, 25 Nov 2024 00:23:27 UTC.
// Python implementation: cpython.
// Python-reported platform: Linux-6.9.10-1rodete5-amd64-x86_64-with-glibc2.31.
// Python version: 3.9.6 (default, Nov 21 2024, 22:01:24)  [GCC 10.2.1 20210110].

package internal

var PlatformTags = []PEP425Tag{
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "cp39",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "abi3",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp38",
		ABI:      "abi3",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp37",
		ABI:      "abi3",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp36",
		ABI:      "abi3",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp35",
		ABI:      "abi3",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp34",
		ABI:      "abi3",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp33",
		ABI:      "abi3",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "cp32",
		ABI:      "abi3",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_31_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_30_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_29_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_28_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_27_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_26_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_25_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_24_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_23_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_22_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_21_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_20_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_19_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_18_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_17_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux2014_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_16_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_15_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_14_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_13_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_12_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux2010_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_11_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_10_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_9_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_8_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_7_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_6_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux_2_5_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "manylinux1_x86_64",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "linux_x86_64",
	},
	{
		Python:   "cp39",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py39",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py3",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py38",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py37",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py36",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py35",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py34",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py33",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py32",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py31",
		ABI:      "none",
		Platform: "any",
	},
	{
		Python:   "py30",
		ABI:      "none",
		Platform: "any",
	},
}

var Markers = map[string]string{
	"os_name":                        "posix",
	"sys_platform":                   "linux",
	"platform_machine":               "x86_64",
	"platform_python_implementation": "CPython",
	"platform_release":               "6.9.10-1rodete5-amd64",
	"platform_system":                "Linux",
	"platform_version":               "#1 SMP PREEMPT_DYNAMIC Debian 6.9.10-1rodete5 (2024-09-04)",
	"python_version":                 "3.9",
	"python_full_version":            "3.9.6",
	"implementation_name":            "cpython",
	"implementation_version":         "3.9.6",
}
