// Code generated by "stringer -type AttrKey -output stringer.go"; DO NOT EDIT.

package version

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Blocked - -1]
	_ = x[Deleted - -2]
	_ = x[Error - -4]
	_ = x[Redirect-1]
	_ = x[Features-2]
	_ = x[DerivedFrom-3]
	_ = x[NativeLibrary-4]
	_ = x[Registries-5]
	_ = x[SupportedFrameworks-6]
	_ = x[DependencyGroups-7]
	_ = x[Ident-8]
	_ = x[Created-9]
	_ = x[Tags-10]
}

const (
	_AttrKey_name_0 = "Error"
	_AttrKey_name_1 = "DeletedBlocked"
	_AttrKey_name_2 = "RedirectFeaturesDerivedFromNativeLibraryRegistriesSupportedFrameworksDependencyGroupsIdentCreatedTags"
)

var (
	_AttrKey_index_1 = [...]uint8{0, 7, 14}
	_AttrKey_index_2 = [...]uint8{0, 8, 16, 27, 40, 50, 69, 85, 90, 97, 101}
)

func (i AttrKey) String() string {
	switch {
	case i == -4:
		return _AttrKey_name_0
	case -2 <= i && i <= -1:
		i -= -2
		return _AttrKey_name_1[_AttrKey_index_1[i]:_AttrKey_index_1[i+1]]
	case 1 <= i && i <= 10:
		i -= 1
		return _AttrKey_name_2[_AttrKey_index_2[i]:_AttrKey_index_2[i+1]]
	default:
		return "AttrKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
